"""initial_schema

Revision ID: 32100e704396
Revises: 
Create Date: 2026-09-08 17:48:35.124290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32100e704396'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('algorithm_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='任务名称'),
    sa.Column('type', sa.String(length=32), nullable=False, comment='prediction/recommendation/sentiment'),
    sa.Column('model', sa.String(length=64), nullable=False, comment='模型标识'),
    sa.Column('version', sa.String(length=32), nullable=False, comment='版本号'),
    sa.Column('accuracy', sa.Float(), nullable=False, comment='准确率/评分'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='idle/running/success/failed'),
    sa.Column('last_run_at', sa.DateTime(), nullable=True, comment='最后执行时间'),
    sa.Column('calls', sa.Integer(), nullable=False, comment='调用次数'),
    sa.Column('owner', sa.String(length=64), nullable=False, comment='负责人'),
    sa.Column('config', sa.JSON(), nullable=False, comment='参数配置'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_algorithm_tasks_status'), 'algorithm_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_algorithm_tasks_type'), 'algorithm_tasks', ['type'], unique=False)
    op.create_table('brands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='中文名'),
    sa.Column('name_en', sa.String(length=64), nullable=False, comment='英文名'),
    sa.Column('country', sa.String(length=32), nullable=False, comment='国别'),
    sa.Column('group', sa.String(length=32), nullable=False, comment='阵营：自主/新势力/德系/日系/美系/韩系/欧系'),
    sa.Column('color', sa.String(length=16), nullable=False, comment='品牌主色'),
    sa.Column('founded_year', sa.Integer(), nullable=False, comment='成立年份'),
    sa.Column('energy_focus', sa.JSON(), nullable=False, comment='主打能源类型'),
    sa.Column('weight', sa.Integer(), nullable=False, comment='市场规模权重（相对值）'),
    sa.Column('model_count', sa.Integer(), nullable=False, comment='在售车型数'),
    sa.Column('annual_sales', sa.Integer(), nullable=False, comment='年销量（辆）'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='active/inactive'),
    sa.Column('source', sa.String(length=64), nullable=False, comment='数据来源'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('collection_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False, comment='来源域名/系统'),
    sa.Column('source_url', sa.String(length=512), nullable=True, comment='源 URL'),
    sa.Column('collected_at', sa.DateTime(), nullable=False, comment='数据截止时间'),
    sa.Column('data_period', sa.String(length=16), nullable=False, comment='数据周期（如 2026-08）'),
    sa.Column('record_count', sa.Integer(), nullable=False, comment='提取记录数'),
    sa.Column('passed_count', sa.Integer(), nullable=False, comment='清洗通过数'),
    sa.Column('fixed_count', sa.Integer(), nullable=False, comment='修复记录数'),
    sa.Column('quarantined_count', sa.Integer(), nullable=False, comment='隔离记录数'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='success/partial/error'),
    sa.Column('error_message', sa.String(length=512), nullable=True, comment='错误摘要'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'collected_at', name='uq_collection_log')
    )
    op.create_index(op.f('ix_collection_logs_collected_at'), 'collection_logs', ['collected_at'], unique=False)
    op.create_index(op.f('ix_collection_logs_source'), 'collection_logs', ['source'], unique=False)
    op.create_table('data_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False, comment='文件名'),
    sa.Column('size', sa.Integer(), nullable=False, comment='文件大小（字节）'),
    sa.Column('type', sa.String(length=32), nullable=False, comment='文件类型：csv/json/xlsx'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='pending/parsing/loaded/error'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='进度 %'),
    sa.Column('rows', sa.Integer(), nullable=False, comment='入库行数'),
    sa.Column('message', sa.String(length=512), nullable=True, comment='错误消息'),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False, comment='上传时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('energy_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('energy_type', sa.String(length=8), nullable=False, comment='BEV/PHEV/EREV/HEV/ICE'),
    sa.Column('month', sa.Date(), nullable=False, comment='月份'),
    sa.Column('sales', sa.Integer(), nullable=False, comment='销量（辆）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('energy_type', 'month', name='uq_energy_sales_type_month')
    )
    op.create_index(op.f('ix_energy_sales_energy_type'), 'energy_sales', ['energy_type'], unique=False)
    op.create_table('regions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False, comment='省份名称'),
    sa.Column('weight', sa.Float(), nullable=False, comment='市场份额权重'),
    sa.Column('penetration', sa.Float(), nullable=False, comment='新能源渗透率 %'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False, comment='登录账号'),
    sa.Column('nickname', sa.String(length=64), nullable=False, comment='昵称'),
    sa.Column('email', sa.String(length=128), nullable=False, comment='邮箱'),
    sa.Column('phone', sa.String(length=32), nullable=False, comment='手机号'),
    sa.Column('password_hash', sa.String(length=128), nullable=False, comment='bcrypt 哈希'),
    sa.Column('role', sa.String(length=16), nullable=False, comment='admin/analyst/sales/user'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='active/disabled/pending'),
    sa.Column('department', sa.String(length=64), nullable=False, comment='部门'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('last_login_ip', sa.String(length=64), nullable=True, comment='最后登录 IP'),
    sa.Column('login_count', sa.Integer(), nullable=False, comment='登录次数'),
    sa.Column('car_count', sa.Integer(), nullable=False, comment='关注的车型数'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username', name='uq_user_username')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('brand_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False, comment='品牌 ID'),
    sa.Column('alias', sa.String(length=128), nullable=False, comment='别名'),
    sa.Column('source', sa.String(length=64), nullable=False, comment='别名来源'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias', name='uq_brand_alias')
    )
    op.create_index(op.f('ix_brand_aliases_alias'), 'brand_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_brand_aliases_brand_id'), 'brand_aliases', ['brand_id'], unique=False)
    op.create_table('brand_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False, comment='品牌 ID'),
    sa.Column('month', sa.Date(), nullable=False, comment='月份'),
    sa.Column('sales', sa.Integer(), nullable=False, comment='销量（辆）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'month', name='uq_brand_sales_brand_month')
    )
    op.create_index(op.f('ix_brand_sales_brand_id'), 'brand_sales', ['brand_id'], unique=False)
    op.create_table('cars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False, comment='品牌 ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='车型显示名'),
    sa.Column('name_norm', sa.String(length=128), nullable=False, comment='清洗归一名（去空格/动力修饰）'),
    sa.Column('model_code', sa.String(length=32), nullable=False, comment='车型代号'),
    sa.Column('category', sa.String(length=16), nullable=False, comment='轿车/SUV/MPV/跑车/皮卡'),
    sa.Column('energy_type', sa.String(length=8), nullable=False, comment='BEV/PHEV/EREV/HEV/ICE'),
    sa.Column('price', sa.Float(), nullable=False, comment='指导价（万元）'),
    sa.Column('price_min', sa.Float(), nullable=False, comment='终端起售价（万元）'),
    sa.Column('price_max', sa.Float(), nullable=False, comment='终端顶配价（万元）'),
    sa.Column('range_km', sa.Integer(), nullable=False, comment='纯电续航（km）'),
    sa.Column('battery_kwh', sa.Float(), nullable=False, comment='电池容量（kWh）'),
    sa.Column('power_kw', sa.Integer(), nullable=False, comment='最大功率（kW）'),
    sa.Column('torque_nm', sa.Integer(), nullable=False, comment='峰值扭矩（N·m）'),
    sa.Column('wheelbase', sa.Integer(), nullable=False, comment='轴距（mm）'),
    sa.Column('length', sa.Integer(), nullable=False, comment='车长（mm）'),
    sa.Column('width', sa.Integer(), nullable=False, comment='车宽（mm）'),
    sa.Column('height', sa.Integer(), nullable=False, comment='车高（mm）'),
    sa.Column('seats', sa.Integer(), nullable=False, comment='座位数'),
    sa.Column('launch_date', sa.Date(), nullable=False, comment='上市时间'),
    sa.Column('launch_year', sa.Integer(), nullable=False, comment='上市年份'),
    sa.Column('sales_12m', sa.Integer(), nullable=False, comment='近 12 个月销量'),
    sa.Column('last_month_sales', sa.Integer(), nullable=False, comment='上月销量'),
    sa.Column('rating', sa.Float(), nullable=False, comment='用户评分 0~5'),
    sa.Column('intelligence_score', sa.Integer(), nullable=False, comment='智能化评分'),
    sa.Column('comfort_score', sa.Integer(), nullable=False, comment='舒适性评分'),
    sa.Column('space_score', sa.Integer(), nullable=False, comment='空间评分'),
    sa.Column('performance_score', sa.Integer(), nullable=False, comment='性能评分'),
    sa.Column('review_count', sa.Integer(), nullable=False, comment='评价数'),
    sa.Column('rank', sa.Integer(), nullable=True, comment='销量排名'),
    sa.Column('tags', sa.JSON(), nullable=False, comment='标签'),
    sa.Column('image', sa.String(length=255), nullable=True, comment='车型图片 URL'),
    sa.Column('source', sa.String(length=64), nullable=False, comment='数据来源'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'name_norm', 'energy_type', name='uq_car_brand_name_energy'),
    sa.UniqueConstraint('model_code')
    )
    op.create_index(op.f('ix_cars_brand_id'), 'cars', ['brand_id'], unique=False)
    op.create_index(op.f('ix_cars_category'), 'cars', ['category'], unique=False)
    op.create_index(op.f('ix_cars_energy_type'), 'cars', ['energy_type'], unique=False)
    op.create_index(op.f('ix_cars_launch_year'), 'cars', ['launch_year'], unique=False)
    op.create_index('ix_cars_price', 'cars', ['price'], unique=False)
    op.create_index('ix_cars_sort_sales', 'cars', ['sales_12m'], unique=False)
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户 ID'),
    sa.Column('action', sa.String(length=64), nullable=False, comment='操作类型'),
    sa.Column('module', sa.String(length=32), nullable=False, comment='模块'),
    sa.Column('target', sa.String(length=128), nullable=False, comment='目标对象'),
    sa.Column('ip', sa.String(length=64), nullable=True, comment='客户端 IP'),
    sa.Column('result', sa.String(length=16), nullable=False, comment='success/failure'),
    sa.Column('detail', sa.String(length=512), nullable=True, comment='详情'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_logs_action'), 'operation_logs', ['action'], unique=False)
    op.create_index(op.f('ix_operation_logs_module'), 'operation_logs', ['module'], unique=False)
    op.create_index(op.f('ix_operation_logs_result'), 'operation_logs', ['result'], unique=False)
    op.create_index(op.f('ix_operation_logs_user_id'), 'operation_logs', ['user_id'], unique=False)
    op.create_table('regional_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False, comment='地区 ID'),
    sa.Column('month', sa.Date(), nullable=False, comment='月份'),
    sa.Column('energy_type', sa.String(length=8), nullable=True, comment='能源类型（NULL=全部）'),
    sa.Column('brand_id', sa.Integer(), nullable=True, comment='品牌 ID（NULL=全部）'),
    sa.Column('sales', sa.Integer(), nullable=False, comment='销量（辆）'),
    sa.Column('source', sa.String(length=64), nullable=False, comment='来源（公开明细 unavailable 时为 estimated）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'month', 'energy_type', 'brand_id', name='uq_regional_sales')
    )
    op.create_index(op.f('ix_regional_sales_region_id'), 'regional_sales', ['region_id'], unique=False)
    op.create_table('car_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False, comment='车型 ID'),
    sa.Column('month', sa.Date(), nullable=False, comment='月份 YYYY-MM-01'),
    sa.Column('sales', sa.Integer(), nullable=False, comment='销量（辆，>0）'),
    sa.Column('revenue', sa.Float(), nullable=False, comment='销售额（万元）'),
    sa.Column('source', sa.String(length=64), nullable=False, comment='数据来源'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id', 'month', name='uq_car_sales_car_month')
    )
    op.create_index(op.f('ix_car_sales_car_id'), 'car_sales', ['car_id'], unique=False)
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False, comment='车型 ID'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='当前库存（辆）'),
    sa.Column('inbound', sa.Integer(), nullable=False, comment='本月入库'),
    sa.Column('monthly_sales', sa.Integer(), nullable=False, comment='上月销量'),
    sa.Column('turnover_days', sa.Float(), nullable=False, comment='周转天数'),
    sa.Column('warehouse', sa.String(length=64), nullable=False, comment='仓库名称'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='紧张/偏低/充足'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventories_car_id'), 'inventories', ['car_id'], unique=False)
    op.create_table('model_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False, comment='车型 ID'),
    sa.Column('alias', sa.String(length=128), nullable=False, comment='别名'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id', 'alias', name='uq_model_alias')
    )
    op.create_index(op.f('ix_model_aliases_alias'), 'model_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_model_aliases_car_id'), 'model_aliases', ['car_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False, comment='订单号'),
    sa.Column('car_id', sa.Integer(), nullable=False, comment='车型 ID'),
    sa.Column('customer', sa.String(length=128), nullable=False, comment='客户名'),
    sa.Column('amount', sa.Float(), nullable=False, comment='金额（万元）'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='pending/paid/shipped/completed/cancelled'),
    sa.Column('region', sa.String(length=32), nullable=False, comment='地区'),
    sa.Column('salesperson', sa.String(length=64), nullable=True, comment='销售员'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no'),
    sa.UniqueConstraint('order_no', name='uq_order_no')
    )
    op.create_index(op.f('ix_orders_car_id'), 'orders', ['car_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_hash', sa.String(length=32), nullable=False, comment='请求指纹 MD5'),
    sa.Column('request_body', sa.JSON(), nullable=False, comment='原始请求'),
    sa.Column('car_id', sa.Integer(), nullable=False, comment='车型 ID'),
    sa.Column('score', sa.Float(), nullable=False, comment='综合匹配度 0~100'),
    sa.Column('rank_no', sa.Integer(), nullable=False, comment='本次请求内排名'),
    sa.Column('reason', sa.String(length=500), nullable=True, comment='推荐理由'),
    sa.Column('model_name', sa.String(length=64), nullable=False, comment='算法标识'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_car_id'), 'recommendations', ['car_id'], unique=False)
    op.create_index(op.f('ix_recommendations_request_hash'), 'recommendations', ['request_hash'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False, comment='车型 ID'),
    sa.Column('brand_id', sa.Integer(), nullable=False, comment='品牌 ID（冗余便于按品牌聚合）'),
    sa.Column('user_name', sa.String(length=64), nullable=False, comment='评价人'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='评分 1~5'),
    sa.Column('content', sa.String(length=2000), nullable=False, comment='评价内容'),
    sa.Column('published_at', sa.Date(), nullable=False, comment='发布日期'),
    sa.Column('likes', sa.Integer(), nullable=False, comment='点赞数'),
    sa.Column('source', sa.String(length=64), nullable=False, comment='来源平台'),
    sa.Column('source_url', sa.String(length=512), nullable=True, comment='来源 URL'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_brand_id'), 'reviews', ['brand_id'], unique=False)
    op.create_index(op.f('ix_reviews_car_id'), 'reviews', ['car_id'], unique=False)
    op.create_index(op.f('ix_reviews_published_at'), 'reviews', ['published_at'], unique=False)
    op.create_table('sales_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False, comment='车型 ID'),
    sa.Column('prediction_month', sa.Date(), nullable=False, comment='预测月份'),
    sa.Column('predicted_sales', sa.Integer(), nullable=False, comment='预测销量（辆）'),
    sa.Column('lower', sa.Integer(), nullable=False, comment='置信下界'),
    sa.Column('upper', sa.Integer(), nullable=False, comment='置信上界'),
    sa.Column('model_name', sa.String(length=64), nullable=False, comment='模型名'),
    sa.Column('accuracy', sa.Float(), nullable=False, comment='验证集准确率 0~1'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id', 'prediction_month', 'model_name', name='uq_prediction_car_month_model')
    )
    op.create_index(op.f('ix_sales_predictions_car_id'), 'sales_predictions', ['car_id'], unique=False)
    op.create_table('sentiments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False, comment='评价 ID'),
    sa.Column('label', sa.String(length=16), nullable=False, comment='positive/neutral/negative'),
    sa.Column('score', sa.Float(), nullable=False, comment='情感分 0~1'),
    sa.Column('keywords', sa.JSON(), nullable=False, comment='命中关键词'),
    sa.Column('model_name', sa.String(length=64), nullable=False, comment='分析模型'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', name='uq_sentiment_review')
    )
    op.create_index(op.f('ix_sentiments_label'), 'sentiments', ['label'], unique=False)
    op.create_index(op.f('ix_sentiments_review_id'), 'sentiments', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiments_review_id'), table_name='sentiments')
    op.drop_index(op.f('ix_sentiments_label'), table_name='sentiments')
    op.drop_table('sentiments')
    op.drop_index(op.f('ix_sales_predictions_car_id'), table_name='sales_predictions')
    op.drop_table('sales_predictions')
    op.drop_index(op.f('ix_reviews_published_at'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_car_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_brand_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_recommendations_request_hash'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_car_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_car_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_model_aliases_car_id'), table_name='model_aliases')
    op.drop_index(op.f('ix_model_aliases_alias'), table_name='model_aliases')
    op.drop_table('model_aliases')
    op.drop_index(op.f('ix_inventories_car_id'), table_name='inventories')
    op.drop_table('inventories')
    op.drop_index(op.f('ix_car_sales_car_id'), table_name='car_sales')
    op.drop_table('car_sales')
    op.drop_index(op.f('ix_regional_sales_region_id'), table_name='regional_sales')
    op.drop_table('regional_sales')
    op.drop_index(op.f('ix_operation_logs_user_id'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_result'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_module'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_action'), table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_index('ix_cars_sort_sales', table_name='cars')
    op.drop_index('ix_cars_price', table_name='cars')
    op.drop_index(op.f('ix_cars_launch_year'), table_name='cars')
    op.drop_index(op.f('ix_cars_energy_type'), table_name='cars')
    op.drop_index(op.f('ix_cars_category'), table_name='cars')
    op.drop_index(op.f('ix_cars_brand_id'), table_name='cars')
    op.drop_table('cars')
    op.drop_index(op.f('ix_brand_sales_brand_id'), table_name='brand_sales')
    op.drop_table('brand_sales')
    op.drop_index(op.f('ix_brand_aliases_brand_id'), table_name='brand_aliases')
    op.drop_index(op.f('ix_brand_aliases_alias'), table_name='brand_aliases')
    op.drop_table('brand_aliases')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_table('regions')
    op.drop_index(op.f('ix_energy_sales_energy_type'), table_name='energy_sales')
    op.drop_table('energy_sales')
    op.drop_table('data_files')
    op.drop_index(op.f('ix_collection_logs_source'), table_name='collection_logs')
    op.drop_index(op.f('ix_collection_logs_collected_at'), table_name='collection_logs')
    op.drop_table('collection_logs')
    op.drop_table('brands')
    op.drop_index(op.f('ix_algorithm_tasks_type'), table_name='algorithm_tasks')
    op.drop_index(op.f('ix_algorithm_tasks_status'), table_name='algorithm_tasks')
    op.drop_table('algorithm_tasks')
    # ### end Alembic commands ###
